# Generated by Django 4.0.6 on 2022-08-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_order_tags_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date_created',
        ),
        migrations.AddField(
            model_name='customer',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
